### PR TITLE
Add spanish translation.

### PR DESCRIPTION
**Pull request by mayra-cabrera**
Related to #140

This is a first approach of an Spanish translation, it would be good to have another native Spanish speaker to take a look.

### CODE REVIEW

**Comment by joseluistorres** [comment]
I couldn't do it better myself @mayra-cabrera @CoralineAda, it looks good to me!

**Comment by CoralineAda** [comment]
Would it be a bad thing to leave Contributor Covenant in English at the bottom of the document?

**Comment by joseluistorres** [comment]
IMO it will be ok, since it's in the context of that original document

**Comment by CoralineAda** [comment]
Can you please do that @mayra-cabrera? Then I'll be happy to merge!

**Comment by mayra-cabrera** [comment]
Awesome :smile_cat: , I already made the change ! @CoralineAda 

Thanks @joseluistorres for your review

**Pull request merged**
