### PR TITLE
Minimalist Re-design

### PR DESCRIPTION
**Pull request by lewisgoddard**
- Comply with accessibility standards.
- Add code style guidelines.
- Move tabular data to a more sensible format.
- Make responsive down to `320px`.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I like everything you did except for getting rid of the background. Happy to merge once that's back in place. Note that I'm open to toning down the colors for the sake of readability, but black on a plain white background is too much for me. Thanks!

**Comment by lewisgoddard** [comment]
Would you consider a more clean cut background, with some stripes of softer, solid color? The fade in is what caused me real issues, as backgrounds generally shouldn't change under text. Maybe something from [this color palette](https://color.adobe.com/create/color-wheel/?base=2&rule=Compound&selected=2&name=My%20Color%20Theme&mode=rgb&rgbvalues=0.8,0.4873213327770993,0.6674201695454403,0.6,0.18549099958282447,0.42424278098249085,0.9086228094226133,0.7091516659713741,1,1,0.9852641458846901,0.4876412524050291,0.8,0.759487080393088,0.4873213327770993&swatchOrder=0,1,2,3,4).

**Comment by CoralineAda** [comment]
Absolutely. Give it a shot!

**Comment by lewisgoddard** [comment]
I'm actually quite please with how this is turning out. The header is full-width and it's background matches the new link color, and the header underline and blockquote bar match. It's still quite bold initially, but is more subtle touches of color for the main text.

screenshot from 2016-01-21 23 31 56

**Comment by CoralineAda** [comment]
Can you make the body text wider, or the header not full-width? It looks like a bit too much whitespace to me.

**Comment by lewisgoddard** [comment]
I've bumped it to `60rem`, I think much wider and it starts getting difficult to read. I made the header no full-width too and added a border. I just want to make that responsive.

**Comment by lewisgoddard** [comment]
Okay, that should make the header full-width when there's not much space, but pull in to the content width when there is.

**Comment by lewisgoddard** [comment]
### Large
screenshot from 2016-01-21 23 49 35

### Small
screenshot from 2016-01-21 23 50 07

**Comment by CoralineAda** [comment]
Looking good! I'm not sure how I feel about the rounded corners on the header though.

**Comment by lewisgoddard** [comment]
I think it looks odd without them, and even odder with the border up the sides.

screenshot from 2016-01-21 23 54 49

**Comment by CoralineAda** [comment]
I rather like this.

**Comment by lewisgoddard** [comment]
What about a slight rounding that doesn't go past the border?

screenshot from 2016-01-22 00 09 25

**Comment by CoralineAda** [comment]
Yep, that’s nice!

**Comment by lewisgoddard** [comment]
Okay, I've implemented.

**Comment by CoralineAda** [comment]
Can you fix the columns on adopters/index.html?

**Comment by CoralineAda** [comment]
Also this page needs some love: version/1/3/0/i18n/index.html

**Comment by lewisgoddard** [comment]
Are those three the only stylized pages?

**Comment by CoralineAda** [comment]
Yes.

**Comment by lewisgoddard** [comment]
I think I'm done now, unless there's anything else?

**Comment by CoralineAda** [comment]
Thanks Lewis! This is great.

**Pull request merged**
