### PR TITLE
Add Twisted to the adopters list

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by CoralineAda** [comment]
Hey, looks good except I limit the number of projects that I list on the main index.html. Can you please remove it from there?

**Comment by hawkowl** [comment]
Okay! Bit unfortunate there's no Python projects on the front page though :(

**Comment by hawkowl** [comment]
force pushed, refresh :)

**Comment by CoralineAda** [comment]
Any idea how many users you have?

**Comment by hawkowl** [comment]
Developers, in the thousands (we've got 1,000 GitHub stars if that's any indicator) -- end users, probably a few tens of millions :). Twisted works its way into all sorts of places. The project's also 15 years old, which helps -- and was the direct inspiration for Mochi Deferreds, jQuery Deferreds, and eventually Promises/A.

**Comment by CoralineAda** [comment]
OK, let's put you on the home page. :)

**Comment by CoralineAda** [comment]
Done!

**Comment by hawkowl** [comment]
Yaaaaay :snake: :snake: :snake:

**Pull request merged**
